### ISSUE TITLE
Provider state shown incorrectly when switched for requestor mode on Linux

### ISSUE THREAD

**Issue by ederenn** [golemfactory/golem-electron#475] opened 2018-11-09 20:27 UTC
#### Encountered on:
Linux, rc 0.18.2 build 3000

in this version of Golem  in GUI provider state jumps between "Idle" and "Waiting for task"
When Golem stopped in "Waiting for task" and switched to requesting mode "I want to act only as Requestor" after starting app the same state is shown in interface. Correctly it should be "Not accepting tasks"

<img width="493" alt="screen shot 2018-11-09 at 14 19 01" src="https://user-images.githubusercontent.com/32061891/48286414-d6b7ce00-e465-11e8-9c5b-54f11ba7cd2d.png">

<img width="520" alt="screen shot 2018-11-09 at 14 23 29" src="https://user-images.githubusercontent.com/32061891/48286424-de777280-e465-11e8-8e27-0a3c0743d411.png">

**Comment by mdtanrikulu** [comment] 2018-11-13 12:43
Couldn't reproduce it on Ubuntu, anything specific that I missed @ederenn ?

**Comment by ederenn** [comment] 2018-11-13 13:10
you need to stop Golem when it is specifically in "Waiting for task" state. Then it is reproducible.

**Comment by mdtanrikulu** [comment] 2019-02-05 19:26
Fixed in b0.1.19.

**Closed as completed by mdtanrikulu** 2019-02-05 19:26 UTC
Labels: bug, Linux
